[package]
name = "pilka"
version = "0.2.3"
authors = ["Alex Komissarov <k.a.komissar@gmail.com>"]
edition = "2018"
license = "GPL-2.0-or-later"
description = "Another democoding tool for creative coding with shaders."
repository = "https://github.com/pudnax/pilka/"
readme = "README.md"
keywords = ["graphics", "glsl", "shaders", "shadertoy", "creative", "vulkan"]
exclude = [".gitignore", ".github", "screenshots", "records", "shader_dump"]
categories = ["command-line-utilities", "Graphics", "Rendering"]

[badges]
appveyor = { repository = "https://github.com/pudnax/pilka", branch = "master", service = "github" }
maintenance = { status = "experimental" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["libs/*"]

[dependencies]
color-eyre = "0.5.8"
eyre = "0.6.3"
pilka_lib = { version = "0.2.3", path = "libs/pilka_lib" }
pilka_dyn = { version = "0.2.3", path = "libs/pilka_dyn" }
notify = "5.0.0-pre.4"
chrono = "0.4.19"
png = "0.16.8"
cpal = "0.13.1"

[profile.release]
lto = 'thin'

# [profile.dev.package.'*']
# opt-level = 3

# [profile.dev]
# debug = 0
